NFOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings


app_name = 'app'  # here for namespacing of urls.

urlpatterns = [
    # Index Page (HOME)
    path('', views.index, name="index"),

    # About Page
    path('about', TemplateView.as_view(template_name='app/about.html'), name="about"),
    
    # Contact Us Page
    path('contact', views.contact, name="contact"),

    # Register Page
    path('signup', views.signup, name="signup"),

    # Login/Logout Page
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),

    # Donate Page
    path('donate', TemplateView.as_view(template_name='app/donate.html'), name="donate"),

    # Events Page
    path('events', views.events, name="events"),

    # Subscribe 
    path('subscribe', views.subscribe_email, name='subscribe_email'),

    # Members Area Pages
    path('member', views.member, name="member"),
    path('member/edit', views.editinfo, name="edit_member"),
    path('member/forms', views.forms, name="forms"),
    path('member/upload/member', views.upload_member, name="upload_member"),
    path('member/upload/police', views.upload_police, name="upload_police"),

    # Account Changes Pages
    path('password/forgot', views.password_forgot, name="forgot_password"),
    path('password/forgot/done', auth_views.PasswordResetDoneView.as_view(template_name='app/password/password_forgot_done.html'), name="forgot_password_done"),
    path('password/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='app/password/password_reset.html', success_url=reverse_lazy('app:reset_password_done')), name="reset_password"),
    path('password/reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='app/password/password_reset_done.html',), name="reset_password_done"),
    path('username/forgot', views.username_forgot, name="forgot_username"),
    path('username/forgot/done', TemplateView.as_view(template_name='app/account/username_forgot_done.html'), name="forgot_username_done")
    
]

if settings.DEBUG:
    # Test Page (Replace Template name with custom html to view the page)
    urlpatterns.append(path('test/', TemplateView.as_view(template_name='app/index.html'), name="test"))

templates/app/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/app/about.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/app/partials/banner.js' %}"></script>
{% endblock %}

{% block content %}
<!-- Top-Banner -->
{% include "app/partials/banner.html" %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="about" class="full-background">
  <div class="about-info text-center">
    <div class="container px-3">
      <h1>Newark Fraternal Order of Police</h1>
      <p class="lead py-1">The Newark Fraternal Order of Police Lodge #12 is an active Union Office that represents about 
        850 active police officers and over 700 retirees. We protect our officers rights in incidents
        where an officer has taken legal action while on or off duty. We negotiate for their benefits,
        salaries and work schedules. Along with just being an active lodge. We also have great support 
        from within our communities that become associate memebers and show their support for our law 
        enforcement community. With their support we donate to various organizations.
      </p>
    </div>
  </div>
  <div class="team-info mb-5 text-center">
    <h2 class="pt-4 pb-2 display-5">Meet our team</h2>
      <div class="row g-0 justify-content-center">
        <div class="card shadow py-2 align-items-center" style="width: 25rem;">
          <img src="{% static 'assets/team/pres.jpg' %}" class="card-img-top" style="object-position: 0 40%;" alt="President">
          <div class="card-body">
            <h5 class="card-title">James Stewart Jr.</h5>
            <p class="text-muted">President</p>
            <p>stewee68@comcast.net</p>
            <p>732-991-0689</p>
            <a href="mailto:stewee68@comcast.net" class="btn btn-outline-primary">Contact</a>
          </div>
        </div>
        <div class="card shadow py-2 align-items-center" style="width: 25rem;">
          <img src="{% static 'assets/team/vp.jpg' %}" class="card-img-top" style="object-position: 0 30%;" alt="President">
          <div class="card-body">
            <h5 class="card-title">Walter Melvin</h5>
            <p class="text-muted">Vice President</p>
            <p>wal6425@aol.com</p>
            <p>973-642-0390</p>
            <a href="mailto:wal6425@aol.com" class="btn btn-outline-primary">Contact</a>
          </div>
        </div>
      </div>
      <div class="row g-0 justify-content-center">
        <div class="card shadow py-2  align-items-center" style="width: 25rem;">
          <img src="{% static 'assets/team/tres.jpg' %}" class="card-img-top" style="object-position: 0 30%;" alt="President">
          <div class="card-body">
            <h5 class="card-title">Ariel Cortez</h5>
            <p class="text-muted">Treasurer</p>
            <p>acortez@newarkfop.com</p>
            <p>732-642-0390</p>
            <a href="mailto:acortez@newarkfop.com" class="btn btn-outline-primary">Contact</a>
          </div>
        </div>
        <div class="card shadow py-2 align-items-center" style="width: 25rem;">
          <img src="{% static 'assets/team/sec.jpg' %}" class="card-img-top" style="object-position: 0 30%;" alt="President">
          <div class="card-body">
            <h5 class="card-title">Daniel P. Eames</h5>
            <p class="text-muted">Secretary</p>
            <p>nwrkfop@aol.com</p>
            <p>732-642-0390</p>
            <a href="mailto:nwrkfop@aol.com" class="btn btn-outline-primary">Contact</a>
          </div>
        </div>
        <div class="card shadow py-2 align-items-center" style="width: 25rem;">
          <img src="{% static 'assets/team/om.jpg' %}" class="card-img-top" style="object-position: 0 50%;" alt="President">
          <div class="card-body">
            <h5 class="card-title">Robert D'Angelo</h5>
            <p class="text-muted">Office Manager</p>
            <p>nwrkfop@aol.com</p>
            <p>732-642-0390</p>
            <a href="mailto:nwrkfop@aol.com" class="btn btn-outline-primary">Contact</a>
          </div>
        </div>
    </div>
  </div>
</section>
{% endblock %}

templates/app/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}

{% block vendor %}
<link rel="stylesheet" href="{% static 'css/app/contact.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/app/contact.js' %}"></script>
<script type="text/javascript" src="{% static 'js/app/partials/banner.js' %}"></script>
{% endblock %}

{% block content %}
<!-- Top-Banner -->
{% include "app/partials/banner.html" %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="contact" class="full-background">
    <div data-aos="fade-up" class="container my-5">
        <div class="row text-center">
            <h2 class="pt-4 pb-2 display-5">Contact</h2>
            <h5 class="text-muted">We want to hear from you!</h5>
        </div>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                <strong{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</strong>
            </div>
            {% endfor %}
        {% else %}
        {% if contact_form.errors %}
            {% for field in contact_form %}
                {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endfor %}
            {% for error in contact_form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form method="POST" class="row justify-content-center">
            <div class="col-10 col col-md-10 col-lg-6">
                {% csrf_token %}
                <div class="row py-2">
                    <div class="col">
                        <label for="{{contact_form.full_name.id_for_label}}" class="form-label">Full name</label>
                        <input type="text" class="form-control {% if contact_form.full_name.errors %}is-invalid{% endif %}" name="{{contact_form.full_name.name}}" placeholder="Full name" maxlength="200" {% if contact_form.full_name.value %}value="{{contact_form.full_name.value}}"{% endif %} required="" id="{{contact_form.full_name.id_for_label}}">
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        <label for="{{contact_form.email.id_for_label}}" class="form-label">Email</label>
                        <input type="email" class="form-control {% if contact_form.email.errors %}is-invalid{% endif %}" name="{{contact_form.email.name}}" placeholder="Email" maxlength="200" {% if contact_form.email.value %}value="{{contact_form.email.value}}"{%endif %} required="" id="{{contact_form.email.id_for_label}}">
                        <div for="{{contact_form.email.id_for_label}}" class="form-text">We will never share your email.</div>
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        <label for="{{contact_form.subject.id_for_label}}" class="form-label">Subject</label>
                        <input type="text" class="form-control {% if contact_form.subject.errors %}is-invalid{% endif %}" name="{{contact_form.subject.name}}" placeholder="Subject" maxlength="200" {% if contact_form.subject.value %}value="{{contact_form.subject.value}}"{% endif %} required="" id="{{contact_form.subject.id_for_label}}">
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        <label for="{{contact_form.message.id_for_label}}" class="form-label">Message</label>
                        <div class="widget">
                            <span id="char_count" class="text-muted user-select-none"></span>
                            <textarea class="form-control msg_textarea {% if contact_form.message.errors %}is-invalid{% endif %}" name="{{contact_form.message.name}}" rows="10" maxlength="500" onkeyup="countChar(this);" placeholder="Message" required="" id="{{contact_form.message.id_for_label}}">{% if contact_form.message.value %}{{contact_form.message.value}} {% endif %}</textarea>
                        </div>
                    </div>
                </div>
                <div class="d-grid gap-2 pt-4 col-6 mx-auto">
                    <input type="submit" class="btn btn-outline-dark" value="Submit">
                </div>
            </div>
        </form>
        {% endif %}
        <hr class="my-5">
        <div class="location">
            <div class="row g-0 justify-content-center">
                <div class="col-lg-5 col-md-8 col-sm-8 col-11">
                    <div class=" container ratio ratio-4x3">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12091.707144627779!2d-74.1665357!3d40.7416365!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xeac1906558bb4032!2sFraternal%20Order%20of%20Police!5e0!3m2!1sen!2sus!4v1619478656504!5m2!1sen!2sus" style="border:0; width: 100%;" allowfullscreen="" loading="lazy"></iframe>
                    </div>
                </div>
                <div class= "col-lg-5 d-flex align-items-center col-md-8 col-sm-8 col-11">
                  <div class="card-body">
                    <h3 class="card-title">Newark Fraternal Order of Police</h3>
                    <p class="card-text">51 Rector St, Newark, NJ, 07102</p>
                    <p class="card-text"><b>Phone:</b> (973) 642-0390<br><b>Email:</b> nwrkfop@aol.com</p>
                    <div class="row g-0">
                        <div class="col-sm-3 col-4">
                            <p class="card-text"><b>Monday<br>Tuesday<br>Wednesday<br>Thursday<br>Friday<br>Saturday<br>Sunday</b></p>
                        </div>
                        <div class="col">
                            <p class="card-text">8:00 AM - 5:00 PM<br>8:00 AM - 5:00 PM<br>8:00 AM - 5:00 PM<br>8:00 AM - 5:00 PM<br>8:00 AM - 5:00 PM<br>Closed<br>Closed</p>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
        </div> 
    </div>
</section>
{% endblock %}

templates/app/donate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Donate{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/app/donate.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/app/partials/banner.js' %}"></script>
{% endblock %}
{% block content %}
<!-- Top-Banner -->
{% include "app/partials/banner.html" %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}

<section id="donate" >
    <div class="container">
        <div class="donate-info justify-content-center align-items-center">
            <div class="card">
                <div class="row g-0">
                    <div class="col-md-5 col-lg-4">
                        <img src="{% static 'assets/misc/NPDcommunity.jpg' %}" class="img-fluid donate-img" alt="">
                    </div>
                    <div class="col-md-7 col-lg-8">
                        <div class="card-body">
                            <p class="card-text lead text-center fs-3 lh-lg">
                                Your donations to our lodge will enable us to continue
                                to serve the officers and the community in which we serve.
                                <br>
                                Any amount is greately appreciated!
                            </p>
                            <p class="text-center text-muted fs-5"> Please donate using PayPal.</p>
                            
                            <div class="donate-btn text-center">
                                <form action="https://www.paypal.com/donate" method="post" target="_top">
                                    <input type="hidden" name="business" value="lajara239@aol.com" />
                                    <input type="hidden" name="item_name" value="NewarkFOP12 Donation" />
                                    <input type="hidden" name="currency_code" value="USD" />
                                    <input type="image" src="https://i.ibb.co/T4byZmw/paypal-donate-button.png" border="0" height="80" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/app/events.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Events and Calendar{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/app/events.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/app/partials/banner.js' %}"></script>
{% endblock %}
{% block content %}
<!-- Top-Banner -->
{% include "app/partials/banner.html" %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="events" class="full-background">
  <div class="container pb-4 mb-4">
    <div class="welcome-wrapper">
      <div class="welcome-info text-center" style="padding-top: 40px;padding-bottom: 40px;">
        <h2 class="pt-4 pb-2 display-5">Events and Calendar</h2>
      </div>
    </div>
    <div class=" container px-md-2 ratio ratio-16x9">
      <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=cm9vdC5uZm9wQGdtYWlsLmNvbQ&amp;src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%23039BE5&amp;color=%230B8043&amp;title=NewarkFOP12&amp;showNav=1&amp;showDate=0&amp;showCalendars=0&amp;showPrint=0" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
  </div>
</section>
{% endblock %}

templates/app/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/app/login.css' %}" type="text/css" media="screen">
{% endblock %}

{% block content %}     
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %} 
<section id="login" class="py-5">
    <div class="container mt-5 mb-5">
        <div data-aos="fade-up" class="row text-center">
           <div>
               <h1>Login</h1>
            </div>
        </div>
        <form method="POST" class="row justify-content-center">
            <div data-aos="fade-up" class="col-10 col-md-8 col-lg-5">
                {% csrf_token %}
                {% if login_form.errors %}
                    {% for field in login_form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in login_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="wrapper shadow">
                    <div class="row">
                        <div class="col">
                            <label for="{{login_form.username.id_for_label}}" class="form-label">Username</label>
                            <input type="text" class="form-control" placeholder="Username"  name="{{login_form.username.name}}" {% if login_form.username.value %}value="{{login_form.username.value}}"{% endif %} maxlength="15" required="" id="{{login_form.username.id_for_label}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col">
                            <label for="{{login_form.password.id_for_label}}" class="form-label">Password</label>
                            <input type="password" class="form-control" placeholder="**************" name="{{login_form.password.name}}"  required="" id="{{login_form.password.id_for_label}}" aria-autocomplete="list">
                        </div>
                    </div>
                    <br>
                    <div class="row mt-2 mb-5">
                        <div class="d-grid gap-2 col-6 mx-auto">
                            <input type="submit" class="btn btn-outline-dark" value="Login">
                        </div>
                    </div>
                    <div class="form-footer text-center">
                        <div class="row g-0">
                            <div class="col">
                                <p class="text-muted fw-light">Need an account? <a href="{%url 'app:signup' %}">Sign up</a></p>
                            </div>  
                        </div> 
                        <div class="row g-0">
                            <div class="col">
                                <p class="text-muted fw-light">Forgot <a href="{%url 'app:forgot_username' %}">Username</a> or <a href="{%url 'app:forgot_password' %}">Password</a>?</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/app/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sign up{% endblock %}
{% block vendor %}
<script src="https://cdn.jsdelivr.net/npm/jquery-mask-plugin@1.14.16/dist/jquery.mask.min.js"></script>
<script type="text/javascript" src="{% static 'js/app/signup.js' %}"></script>
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="signup" class="full-background">
    <div class="container mt-5 mb-5">
        <div class="row text-center">
            <h1>Sign up</h1>
        </div>
        <form method="POST" class="row justify-content-center">
            <div class="col-10 col-md-8 col-lg-6">
                {% csrf_token %}
                {% if user_form.errors %}
                    {% for field in user_form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in user_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if profile_form.errors %}
                    {% for field in profile_form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in profile_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <div class="col">
                        <label for="{{user_form.username.id_for_label}}" class="form-label">Username</label>
                        <input type="text" class="form-control"  name="{{user_form.username.name}}" placeholder="Username" maxlength="15" minlength="3"  {% if user_form.username.value %}value="{{user_form.username.value}}"{% endif %} required="" id="{{user_form.username.id_for_label}}">
                        <div for="{{user_form.username.id_for_label}}" class="form-text">{{user_form.username.help_text}}</div>        
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col-md-6">
                        <label for="{{user_form.first_name.id_for_label}}" class="form-label">First name</label>
                        <input type="text" class="form-control" name="{{user_form.first_name.name}}" placeholder="First name"  maxlength="35" autofocus="" {% if user_form.first_name.value %}value="{{user_form.first_name.value}}"{% endif %} required="" id="{{user_form.first_name.id_for_label}}">
                    </div>
                    <div class="col-md-6">
                        <label for="{{user_form.lasts_name.id_for_label}}"class="form-label">Last name</label>
                        <input type="text" class="form-control" name="{{user_form.last_name.name}}" placeholder="Last name" maxlength="35" {% if user_form.last_name.value %}value="{{user_form.last_name.value}}"{% endif %} required="" id="{{user_form.lasts_name.id_for_label}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="{{user_form.email.id_for_label}}" class="form-label">Email</label>
                        <input type="email" class="form-control" name="{{user_form.email.name}}" placeholder="user@domain.com" maxlength="254" {% if user_form.email.value %}value="{{user_form.email.value}}"{% endif %} required="" id="{{user_form.email.id_for_label}}">
                        <div for="{{user_form.email.id_for_label}}" class="form-text">{{user_form.email.help_text}}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row g-0">
                            <label for="{{user_form.password1.id_for_label}}" class="form-label">Password</label>
                            <input type="password" class="form-control" name="{{user_form.password1.name}}" placeholder="Enter password" autocomplete="new-password" required="" id="{{user_form.password1.id_for_label}}">
                            <div for="{{user_form.password1.id_for_label}}" class="form-text">{{user_form.password1.help_text}}</div>
                        </div>
                        <div class="row g-0">
                            <label for="{{user_form.password2.id_for_label}}" class="form-label">Confirm password</label>
                            <input type="password" class="form-control" name="{{user_form.password2.name}}" placeholder = "Confirm password" autocomplete="new-password" required="" id="{{user_form.password2.id_for_label}}">
                            <div for="{{user_form.password2.id_for_label}}" class="form-text">{{user_form.password2.help_text}}</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="{{profile_form.address_1.id_for_label}}" class="form-label">Address</label>
                        <input type="text" class="form-control" placeholder="Street address, P.O. box, company name, c/o" name="{{profile_form.address_1.name}}" {% if profile_form.address_1.value %}value="{{profile_form.address_1.value}}"{% endif %} maxlength="128" required="" id="{{profile_form.address_1.id_for_label}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="{{profile_form.address_2.id_for_label}}" class="form-label">Address 2</label>
                        <input type="text" class="form-control" placeholder="Apartment, suite, unit, building, floor, etc." name="{{profile_form.address_2.name}}" {% if profile_form.address_2.value %}value="{{profile_form.address_2.value}}"{% endif %} maxlength="128" id="{{profile_form.address_2.id_for_label}}">    
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col-md-5">
                        <label for="{{profile_form.city.id_for_label}}" class="form-label">City</label>
                        <input type="text" class="form-control" placeholder="City" name="{{profile_form.city.name}}" {% if profile_form.city.value %}value="{{profile_form.city.value}}"{% endif %} maxlength="64" required="" id="{{profile_form.city.id_for_label}}">
                    </div>
                    <div class="col-md-3">
                        <label for="{{profile_form.state.id_for_label}}" class="form-label">State</label>
                        <input type="text" class="form-control" placeholder="State" name="{{profile_form.state.name}}" {% if profile_form.state.value %}value="{{profile_form.state.value}}"{% endif %} maxlength="24" required="" id="{{profile_form.state.id_for_label}}">
                    </div>
                    <div class="col-md-4">
                        <label for="{{profile_form.zip_code.id_for_label}}" class="form-label">Zip code</label>
                        <input type="text" class="form-control" placeholder="Zip code" name="{{profile_form.zip_code.name}}" {% if profile_form.zip_code.value %}value="{{profile_form.zip_code.value}}"{% endif %} maxlength="24" required="" id="{{profile_form.zip_code.id_for_label}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="{{profile_form.phone_number.id_for_label}}" class="form-label">Phone number</label>
                        <input type="text" class="form-control" placeholder="(000) 000-0000" name="{{profile_form.phone_number.name}}" {% if profile_form.phone_number.value %}value="{{profile_form.phone_number.value}}"{% endif %} maxlength="14" required="" id="{{profile_form.phone_number.id_for_label}}">
                    </div>
                </div>
                <div class="row mt-3 mb-3">
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <input type="submit" class="btn btn-outline-dark" value="Sign up">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p class="text-center">Already have an account ? <a href="{% url 'app:login' %}">Login</a></p>
                    </div>  
                </div>  
            </div>
        </form>
    </div>
</section>
{% endblock %}