NFOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings


app_name = 'app'  # here for namespacing of urls.

urlpatterns = [
    # Index Page (HOME)
    path('', views.index, name="index"),

    # About Page
    path('about', TemplateView.as_view(template_name='app/about.html'), name="about"),
    
    # Contact Us Page
    path('contact', views.contact, name="contact"),

    # Register Page
    path('signup', views.signup, name="signup"),

    # Login/Logout Page
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),

    # Donate Page
    path('donate', TemplateView.as_view(template_name='app/donate.html'), name="donate"),

    # Events Page
    path('events', views.events, name="events"),

    # Subscribe 
    path('subscribe', views.subscribe_email, name='subscribe_email'),

    # Members Area Pages
    path('member', views.member, name="member"),
    path('member/edit', views.editinfo, name="edit_member"),
    path('member/forms', views.forms, name="forms"),
    path('member/upload/member', views.upload_member, name="upload_member"),
    path('member/upload/police', views.upload_police, name="upload_police"),

    # Account Changes Pages
    path('password/forgot', views.password_forgot, name="forgot_password"),
    path('password/forgot/done', auth_views.PasswordResetDoneView.as_view(template_name='app/password/password_forgot_done.html'), name="forgot_password_done"),
    path('password/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='app/password/password_reset.html', success_url=reverse_lazy('app:reset_password_done')), name="reset_password"),
    path('password/reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='app/password/password_reset_done.html',), name="reset_password_done"),
    path('username/forgot', views.username_forgot, name="forgot_username"),
    path('username/forgot/done', TemplateView.as_view(template_name='app/account/username_forgot_done.html'), name="forgot_username_done")
    
]

if settings.DEBUG:
    # Test Page (Replace Template name with custom html to view the page)
    urlpatterns.append(path('test/', TemplateView.as_view(template_name='app/index.html'), name="test"))

templates/app/partials/banner.html
{% load static %}
<div id="banner">
    <div class="banner-info align-items-center d-flex">
        <img src="{% static 'assets/logos/nfop-banner.png' %}" class="img-fluid nfop-banner">
        <div class="d-flex ms-auto">
            <div class="social-maillist">
            <div class="social-media justify-content-end text-end">
                <a href="https://www.facebook.com/groups/138607976161088/"><i class="icofont-facebook icofont-2x"></i></a>
                <a href="https://youtu.be/HcZyOtjVjv0 "><i class="icofont-youtube-play icofont-2x"></i></a>
            </div>
            <div class="maillist-modal text-end">
                <a type="text/html" data-bs-toggle="modal" style="text-decoration:none; color: white;" data-bs-target="#subscribeModal" href="javascript:;" onclick="getSubscribeForm()" ><h3>Join our Mailing List</h3></a>
                <p>Stay Up To Date With Our Latest News</p>
            </div>
        </div>
        <div class="modal fade" id="subscribeModal" tabindex="-1" aria-labelledby="subscribeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header text-center">
                  <h5 class="modal-title" id="subscribeModalLabel">Join Our Mailing List!</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <p class="lead">Exclusive content, important information, and frequent updates! Stay up to date with the Newark FOP by joining our mailing list below.</p>
                  <div id="SubscribeForm">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

templates/app/partials/footer.html
{% load static %}
<nav id="footer" class="pt-5 bg-dark">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-3 col-md-4 col-4">
        <h5>Navigation</h5>
        <ul class="list-unstyled">
          <li><a href="{% url 'app:index' %}" class="text-decoration-none text-decoration-none">Home</a></li>
          <li><a href="{% url 'app:about' %}" class="text-decoration-none fs-6">About</a></li>
          <li><a href="{% url 'app:contact' %}" class="text-decoration-none fs-6">Contact</a></li>
          <li><a href="{% url 'app:donate' %}" class="text-decoration-none fs-6">Donate</a></li>
          <li><a href="{% url 'app:events' %}" class="text-decoration-none fs-6">Donate</a></li>
          <li><a href="{% url 'app:signup' %}" class="text-decoration-none fs-6">Sign up</a></li>
          <li><a href="{% url 'app:login' %}" class="text-decoration-none fs-6">Login</a></li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-4 col-4">
        <h5>Updates</h5>
        <ul class="list-unstyled">
          <li><a href="https://www.facebook.com/groups/138607976161088/" class="text-decoration-none fs-6">Newark FOP News</a></li>
          <li><a href="http://www.nj.com" target="_blank" class="text-decoration-none fs-6">NJ News</a></li>
          <li><a href="{% url 'app:events' %}" class="text-decoration-none fs-6">Calendar</a></li>
          <li><a href="https://goo.gl/maps/9pk6bNBeRW5Z8uKm9" class="text-decoration-none fs-6">Map</a></li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-4 col-4 text-wrap">
        <h5>Contact us</h5>
        <p class="fs-6">Address:<br>51 Rector St,<br> Newark, NJ 07102</p>
        <p class="fs-6">Phone:<br>(973)642-0390 </p>
        <p class="fs-6">Fax: <br>(973)642-6378 </p>
      </div>
    </div>
    <hr>
    <div class="footer-info text-center pb-3">
      <div class="row align-middle g-0">
        <div class="col">
          <img src="{% static 'assets/logos/logo.png' %}" class="d-inline" style="height:50px;">
          <div class="d-inline text-muted">&copy;<script>document.write(new Date().getFullYear())</script>, NewarkFOP12
          </div>
          <a href="https://github.com/gajeraYash/NFOP-app">
            <img src="{% static 'assets/logos/ru-cs logo.png' %}" class="d-inline" style="height:55px;" alt="">
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

templates/app/partials/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/app/partials/navbar.css' %}" type="text/css" media="screen">
<nav class="navbar shadow sticky-top navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'app:index' %}">
            <img src="{%static 'assets/logos/logo.png' %}" class="img-fluid" width="50" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:donate' %}">Donate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:events' %}">Events</a>
                </li>
                
            </ul>
            <ul class="navbar-nav me-2">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{user.first_name}} {{user.last_name}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'app:member' %}">Member Info</a></li>
                      <li><a class="dropdown-item" href="{% url 'app:forms' %}">Forms</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:signup' %}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/app/partials/subscribe.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success text-center" role="alert">
        <strong{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</strong>
    </div>
    {% endfor %}
{% else %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-warning" role="alert">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
<form id="subscribeEmailList" method="POST" class="justify-content-center">
    <div class="row g-0 py-2">
        <div class="col">
            <label for="{{form.first_name.id_for_label}}" class="form-label">First name</label> 
        <input type="text" class="form-control" name="{{form.first_name.name}}" {% if form.first_name.value %}value="{{form.first_name.value}}"{% endif %}  maxlength="35" required="" id="{{form.first_name.id_for_label}}">
        </div>
    </div>
    <div class="row g-0 py-2">
        <div class="col">
            <label for="{{form.last_name.id_for_label}}" class="form-label">Last name</label> 
        <input type="text" class="form-control" name="{{form.last_name.name}}" {% if form.last_name.value %}value="{{form.last_name.value}}"{% endif %}  maxlength="35" required="" id="{{form.last_name.id_for_label}}">
        </div>
    </div>
    <div class="row g-0 py-2">
        <div class="col">
            <label for="{{form.email.id_for_label}}" class="form-label">Email</label> 
        <input type="email" class="form-control" name="{{form.email.name}}" {% if form.email.value %}value="{{form.email.value}}"{% endif %} maxlength="254" required="" id="{{form.email.id_for_label}}">
        </div>
    </div>
    <div class="row text-center g-0 py-2">
        <div class="col">
            <input type="submit" class="btn btn-outline-dark" value="Subscribe">
        </div> 
    </div>
</form>
{% endif %}
<script type="text/javascript">
$(document).ready(function () {
    $("#subscribeEmailList").submit(function (e) {
        e.preventDefault();
        $.ajax({
            url: '/subscribe',
            type: "post",
            cache: false,
            data: $("#subscribeEmailList").serialize(),
            dataType: 'html',
            success: function (data) {
                console.log(data)
                $('#SubscribeForm').html(data)
            }
        });
    });
});</script>