NFOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings


app_name = 'app'  # here for namespacing of urls.

urlpatterns = [
    # Index Page (HOME)
    path('', views.index, name="index"),

    # About Page
    path('about', TemplateView.as_view(template_name='app/about.html'), name="about"),
    
    # Contact Us Page
    path('contact', views.contact, name="contact"),

    # Register Page
    path('signup', views.signup, name="signup"),

    # Login/Logout Page
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),

    # Donate Page
    path('donate', TemplateView.as_view(template_name='app/donate.html'), name="donate"),

    # Events Page
    path('events', views.events, name="events"),

    # Subscribe 
    path('subscribe', views.subscribe_email, name='subscribe_email'),

    # Members Area Pages
    path('member', views.member, name="member"),
    path('member/edit', views.editinfo, name="edit_member"),
    path('member/forms', views.forms, name="forms"),
    path('member/upload/member', views.upload_member, name="upload_member"),
    path('member/upload/police', views.upload_police, name="upload_police"),

    # Account Changes Pages
    path('password/forgot', views.password_forgot, name="forgot_password"),
    path('password/forgot/done', auth_views.PasswordResetDoneView.as_view(template_name='app/password/password_forgot_done.html'), name="forgot_password_done"),
    path('password/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='app/password/password_reset.html', success_url=reverse_lazy('app:reset_password_done')), name="reset_password"),
    path('password/reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='app/password/password_reset_done.html',), name="reset_password_done"),
    path('username/forgot', views.username_forgot, name="forgot_username"),
    path('username/forgot/done', TemplateView.as_view(template_name='app/account/username_forgot_done.html'), name="forgot_username_done")
    
]

if settings.DEBUG:
    # Test Page (Replace Template name with custom html to view the page)
    urlpatterns.append(path('test/', TemplateView.as_view(template_name='app/index.html'), name="test"))

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from datetime import datetime
from django.core.validators import FileExtensionValidator
from NFOP.storages import FormStorage

# Create your functions here.

def upload_path(instance, filename):
    _now = datetime.now()
    modelInfo = "Error"
    if (instance._meta.model.__name__ == "PoliceUpload"):
        modelInfo = "police"
    elif (instance._meta.model.__name__ == "MemberUpload"):
        modelInfo = "member"
    date = _now.strftime("%Y-%m-%d")
    time = _now.strftime("%I.%M.%S.%p")
    return '{0}/{1}/{2}_{3}/{4}'.format(instance.user.username,modelInfo, date, time, filename)

def form_storage_path(instance, filename):
    _now = datetime.now()
    ext = filename.split('.')[-1]
    name = filename.split('.')[0]
    modelInfo = instance.get_group_display()
    date = _now.strftime("%Y-%m-%d")
    return '{0}/{1}_{2}.{3}'.format(modelInfo, name, date, ext)

# Create your models here.
class UserProfile (models.Model):
    user = models.OneToOneField(User, default="", on_delete=CASCADE)
    address_1 = models.CharField(max_length=128)
    address_2 = models.CharField(max_length=128, blank=True)

    city = models.CharField(max_length=64)
    state = models.CharField(max_length=24)
    zip_code = models.CharField(max_length=5)

    phone_number = models.CharField(max_length=14)

    def __str__(self):
        return ( '('+self.user.username + ')\n' 
        + self.user.first_name + ' '  + self.user.last_name 
        + '\nassociated address:\n' 
        + self.address_1 + '\n'
        + self.address_2 + '\n'
        + self.city + ', ' + self.state + ' ' + self.zip_code)
    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profiles'

class UserStatus(models.Model):
    UNVERIFIED = 'UVER'
    MEMBER = 'MEMB'
    POLICE = 'POLI'

    STATUS_CHOICES = [
        (UNVERIFIED, 'Unverified'),
        (MEMBER, 'Member'),
        (POLICE, 'Police'),
    ]
        
    user = models.OneToOneField(User, on_delete=CASCADE)
    status = models.CharField(choices=STATUS_CHOICES, default=UNVERIFIED, max_length=4)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + ' is a ' +self.status + ' status.'

    def is_authorized(self):
        return self.status in {self.POLICE, self.ACTIVE} 
    
    class Meta:
        verbose_name = 'User Status'
        verbose_name_plural = 'User Status'

class MailList(models.Model):
    first_name = models.CharField(max_length=35)
    last_name = models.CharField(max_length=35)
    email = models.EmailField(max_length=254)

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        return super(MailList, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'MailList Request'
        verbose_name_plural = 'MailList Requests'

    def __str__(self):
        return self.first_name + ' ' + self.last_name + ' - ' + self.email


class FeedbackContact(models.Model):
    full_name = models.CharField(max_length=200,default="")
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        return super(FeedbackContact, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Feedback Contact Request"
        verbose_name_plural = "Feedback Contact Requests"

    def __str__(self):
        return self.full_name + ' - ' + self.subject


class PoliceUpload(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    form = models.FileField(upload_to=upload_path, validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Police Upload"
        verbose_name_plural = "Police Uploads"
    
    def __str__(self):
        return self.user.username + ' - ' + str('{0}'.format(self.date.strftime("%m/%d/%Y")))

class MemberUpload(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    form = models.FileField(upload_to=upload_path)
    frontDL = models.ImageField(upload_to=upload_path)
    backDL = models.ImageField(upload_to=upload_path)
    carReg = models.ImageField(upload_to=upload_path)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Member Upload"
        verbose_name_plural = "Member Uploads"

    def __str__(self):
        return self.user.username + ' - ' + str('{0}'.format(self.date.strftime("%m/%d/%Y")))
class Links(models.Model):
    name = models.CharField(max_length=200)
    link = models.TextField(max_length=500)

    class Meta:
        verbose_name = 'Link'
        verbose_name_plural = 'Links'
    
    def __str__(self):
        return self.name

class DownloadForms(models.Model):
    MEMBER = 'MEMB'
    POLICE = 'POLI'

    GROUP_CHOICE = [
        (MEMBER, 'Member'),
        (POLICE, 'Police'),
    ]
    group = models.CharField(choices=GROUP_CHOICE, primary_key=True, max_length=4)
    form = models.FileField(storage=FormStorage(),upload_to=form_storage_path)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Download Form'
        verbose_name_plural = 'Download Forms'

    def __str__(self):
        return self.group + ' - ' + str(self.date.strftime("%Y-%m-%d"))

templates/app/member/edit_member.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit Member{% endblock %}

{% block vendor %}
<script src="https://cdn.jsdelivr.net/npm/jquery-mask-plugin@1.14.16/dist/jquery.mask.min.js"></script>
<script type="text/javascript" src="{% static 'js/app/member/edit_member.js' %}"></script>
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="home" class="full-background">
  <div class="container py-4">
    <form method="POST" class="row justify-content-center">
      <div class="col-10 col-md-8 col-lg-6">
        {% csrf_token %}
        {% if user_info.errors %}
            {% for field in user_info %}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in user_info.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        {% if profile_info.errors %}
            {% for field in profile_info %}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in profile_info.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row text-center">
          <h4 class="pt-3 display-6">User</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="username_id" class="form-label">Username</label>
            <input type="text" class="form-control" name="username_read" value="{{user.username}}" id="username_id" readonly >
          </div>
        </div>
        <div class="row g-2 pt-1">
          <div class="col-md-6">
              <label for="{{user_info.first_name.id_for_label}}" class="form-label">First name</label>
              <input type="text" class="form-control" name="{{user_info.first_name.name}}" placeholder="First name" value="{{user_info.first_name.value}}"  maxlength="35"  required="" id="{{user_info.first_name.id_for_label}}">
          </div>
          <div class="col-md-6">
              <label for="{{user_info.lasts_name.id_for_label}}" class="form-label">Last name</label>
              <input type="text" class="form-control" name="{{user_info.last_name.name}}" placeholder="Last name" value="{{user_info.last_name.value}}" maxlength="35" required="" id="{{user_info.lasts_name.id_for_label}}">
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
              <label for="{{user_info.email.id_for_label}}" class="form-label">Email</label>
              <input type="email" class="form-control" name="{{user_info.email.name}}" placeholder="user@domain.com" value="{{user_info.email.value}}" maxlength="254" required="" id="{{user_info.email.id_for_label}}">
          </div>
        </div>
        <div class="row text-center">
          <h4 class="pt-3 display-6">Profile</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="{{profile_info.address_1.id_for_label}}" class="form-label">Address</label>
            <input type="text" class="form-control" placeholder="Street address, P.O. box, company name, c/o" name="{{profile_info.address_1.name}}" value="{{profile_info.address_1.value}}" maxlength="128" required="" id="{{profile_info.address_1.id_for_label}}">
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
              <label for="{{profile_info.address_2.id_for_label}}" class="form-label">Address 2</label>
              <input type="text" class="form-control" placeholder="Apartment, suite, unit, building, floor, etc." name="{{profile_info.address_2.name}}" value="{{profile_info.address_2.value}}" maxlength="128" id="{{profile_info.address_2.id_for_label}}">    
          </div>
        </div>
        <div class="row pt-1 g-2">
          <div class="col-md-5">
            <label for="{{profile_info.city.id_for_label}}" class="form-label">City</label>
            <input type="text" class="form-control" placeholder="City" name="{{profile_info.city.name}}" value="{{profile_info.city.value}}" maxlength="64" required="" id="{{profile_info.city.id_for_label}}">
          </div>
          <div class="col-md-3">
            <label for="{{profile_info.state.id_for_label}}" class="form-label">State</label>
            <input type="text" class="form-control" placeholder="State" name="{{profile_info.state.name}}" value="{{profile_info.state.value}}" maxlength="24" required="" id="{{profile_info.state.id_for_label}}">
          </div>
          <div class="col-md-4">
            <label for="{{profile_info.zip_code.id_for_label}}" class="form-label">Zip code</label>
            <input type="text" class="form-control" placeholder="Zip code" name="{{profile_info.zip_code.name}}" value="{{profile_info.zip_code.value}}" maxlength="24" required="" id="{{profile_info.zip_code.id_for_label}}">
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
            <label for="{{profile_info.phone_number.id_for_label}}" class="form-label">Phone number</label>
            <input type="text" class="form-control" placeholder="(000) 000-0000" name="{{profile_info.phone_number.name}}" value="{{profile_info.phone_number.value}}" maxlength="14" required="" id="{{profile_info.phone_number.id_for_label}}">
          </div>
        </div>
        <div class="row text-center">
          <h4 class="pt-3 display-6">Status</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="user_status_id" class="form-label">Member status</label>
            <input type="text" class="form-control" name="user_status" value="{{user.userstatus.get_status_display}}" readonly id="user_status_id">    
          </div>
        </div>
        <div class="row g-4 py-4 mt-3 justify-content-center">
          <div class="col-md-6">
            <div class="d-grid mx-auto">
              <input type="submit" class="btn btn-outline-dark" value="Save">
            </div>
          </div>
        </div> 
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/app/member/forms.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Member Only{% endblock %}

{% block vendor %}
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section class="forms full-background" id="forms">
    <div class="container">
        <div class="row g-0 justify-content-center my-5 py-5">
            <div class="card w-75 text-center my-3">
                <div class="card-header">
                    <h5 class="card-title">Member</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">For new and current active members.</p>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'app:upload_member' %}" class="btn btn-outline-dark">Upload</a>
                        </div>
                        {% if formMember %}
                        <div class="col">
                            <a href="{{formMember.0.form.url}}" class="btn btn-outline-dark" download="">Download</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card w-75 text-center my-3">
                <div class="card-header">
                    <h5 class="card-title">Police</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">Active duty police officers only.</p>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'app:upload_police' %}" class="btn btn-outline-dark">Upload</a>
                        </div>
                        {% if formPolice %}
                        <div class="col">
                            <a href="{{formPolice.0.form.url}}" class="btn btn-outline-dark" download>Download</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-0 justify-content-center text-center">
            <div class="col">
                <h3>Payment</h3>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                    <input type="hidden" name="cmd" value="_xclick">
                    <input type="hidden" name="business" value="lajara239@aol.com">
                    <input type="hidden" name="lc" value="US">
                    <input type="hidden" name="item_name" value="Member Fee">
                    <input type="hidden" name="item_number" value="101">
                    <input type="hidden" name="button_subtype" value="services">
                    <input type="hidden" name="no_note" value="0">
                    <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHostedGuest">
                    <table class="mx-auto">
                    <tr><td><input type="hidden" name="on0" value="Membership">Membership</td></tr><tr><td><select class="form-control" name="os0">
                        <option value="New Member">New Member $145.00 USD</option>
                        <option value="Renewal">Renewal $40.00 USD</option>
                        <option value="Extra Shield">Extra Shield $80.00 USD</option>
                    </select> </td></tr>
                    <tr><td><input type="hidden" name="on1" value="Name and Email">Name and Email</td></tr><tr><td><input type="text" class="form-control" value="{{user.first_name}} {{user.last_name}} - {{user.email}}"name="os1" maxlength="200"></td></tr>
                    </table>
                    <input type="hidden" name="currency_code" value="USD">
                    <input type="hidden" name="option_select0" value="New Member">
                    <input type="hidden" name="option_amount0" value="145.00">
                    <input type="hidden" name="option_select1" value="Renewal">
                    <input type="hidden" name="option_amount1" value="40.00">
                    <input type="hidden" name="option_select2" value="Extra Shield">
                    <input type="hidden" name="option_amount2" value="80.00">
                    <input type="hidden" name="option_index" value="0">
                    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                    </form>
            </div>
        </div>
        
    </div>
</section>
{% endblock %}

templates/app/member/member.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Member Only{% endblock %}

{% block vendor %}
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section id="home" class="full-background">
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-10 col-md-8 col-lg-6">
        <div class="row text-center">
          <h4 class="pt-3 display-6">User</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="username_id" class="form-label">Username</label>
            <input type="text" class="form-control" name="username_read" value="{{user.username}}" id="username_id" readonly >
          </div>
        </div>
        <div class="row g-2 pt-1">
          <div class="col-md-6">
            <label for="first_name_id" class="form-label">First name</label>
            <input type="text" class="form-control" name="first_name_read" value="{{user.first_name}}" id="first_name_id" readonly >
          </div>
          <div class="col-md-6">
            <label for="last_name_id" class="form-label">Last name</label>
            <input type="text" class="form-control" name="last_name_read" value="{{user.last_name}}" id="last_name_id" readonly >
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
            <label for="email_id" class="form-label">Email</label>
            <input type="email" class="form-control" name="email_read" value="{{user.email}}" id="email_id" readonly >
          </div>
        </div>
        <div class="row text-center">
          <h4 class="pt-3 display-6">Profile</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="address_1_id" class="form-label">Address</label>
            <input type="text" class="form-control" name="address_1_read" value="{{user.userprofile.address_1}}" id="address_1_id" readonly >
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
            <label for="address_2_id" class="form-label">Address 2</label>
            <input type="text" class="form-control" name="address_2_read" value="{{user.userprofile.address_2}}" id="address_2_id" readonly >
          </div>
        </div>
        <div class="row pt-1 g-2">
          <div class="col-md-5">
            <label for="city_id" class="form-label">City</label>
            <input type="text" class="form-control" name="city_read" value="{{user.userprofile.city}}" id="city_id" readonly >
          </div>
          <div class="col-md-3">
            <label for="state_id" class="form-label">State</label>
            <input type="text" class="form-control" name="state_read" value="{{user.userprofile.state}}" id="state_id" readonly >
          </div>
          <div class="col-md-4">
            <label for="zip_code_id" class="form-label">Zip code</label>
            <input type="text" class="form-control" name="zip_code_read" value="{{user.userprofile.zip_code}}" id="zip_code_id" readonly >
          </div>
        </div>
        <div class="row pt-1">
          <div class="col">
            <label for="phone_number_id" class="form-label">Phone number</label>
            <input type="text" class="form-control" name="phone_number_read" value="{{user.userprofile.phone_number}}" id="phone_number_id" readonly >
          </div>
        </div>
        <div class="row text-center">
          <h4 class="pt-3 display-6">Status</h4>
        </div>
        <div class="row">
          <div class="col">
            <label for="userstatus_id" class="form-label">Member status</label>
            <input type="text" class="form-control" name="userstatus_read" value="{{user.userstatus.get_status_display}}"
              readonly id="userstatus_id">
          </div>
        </div>
        <div class="row g-4 py-4 mt-3">
          <div class="col-md-6">
            <div class="d-grid mx-auto">
              <a href="{% url 'app:edit_member' %}" class="btn btn-outline-dark">Edit Info</a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="d-grid mx-auto">
              <a href="#" class="btn btn-outline-dark">Change Password</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/app/member/member_upload.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Member Only{% endblock %}

{% block vendor %}
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section class="upload full-background" id="upload">
    <div class="container">
        <div class="info pt-5 text-center">
            <h1>Members Upload</h1>
            <p>Member should upload filled out form, drivers license (front & back) and car registration.</p>
        </div>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                <strong{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</strong>
            </div>
            {% endfor %}
        {% else %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form method="post" class="row justify-content-center" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="col-lg-8 col-md-6">
                    <div class="row g-0 py-2">
                        <label for="{{form.form.id_for_label}}" class="form-label">Form</label>
                        <input class="form-control" name="{{form.form.name}}"type="file" accept=".pdf" required="" id="{{form.form.id_for_label}}">
                    </div>
                    <div class="row g-0 py-2">
                        <label for="{{form.frontDL.id_for_label}}" class="form-label">Front Drivers License</label>
                        <input class="form-control" name="{{form.frontDL.name}}"type="file" accept="image/*" required="" id="{{form.frontDL.id_for_label}}">
                    </div>
                    <div class="row g-0 py-2">
                        <label for="{{form.backDL.id_for_label}}" class="form-label">Back Drivers License</label>
                        <input class="form-control" name="{{form.backDL.name}}"type="file" accept="image/*" required="" id="{{form.backDL.id_for_label}}">
                    </div>
                    <div class="row g-0 py-2">
                        <label for="{{form.carReg.id_for_label}}" class="form-label">Car Registration</label>
                    <input class="form-control" name="{{form.carReg.name}}"type="file" accept="image/*" required="" id="{{form.carReg.id_for_label}}">
                    </div>
                    <div class="row g-0 py-4 justify-content-between">
                        <div class="d-grid col-md-4 col-sm-8 col-6 mx-auto">
                            <input type="submit" class="btn btn-outline-dark" value="Upload">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/app/member/police_upload.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Member Only{% endblock %}

{% block vendor %}
{% endblock %}

{% block content %}
<!-- Navbar -->
{% include "app/partials/navbar.html" with user=user %}
<section class="upload full-background" id="upload">
    <div class="container">
        <div class="info pt-5 text-center">
            <h1>Police Upload</h1>
            <p>Active police officers should upload filled out form.</p>
        </div>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                <strong{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</strong>
            </div>
            {% endfor %}
        {% else %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form method="post" class="row justify-content-center" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="col-lg-8 col-md-6">
                    <div class="row g-0 py-2">
                        <label for="{{form.form.id_for_label}}" class="form-label">Form</label>
                        <input class="form-control" name="{{form.form.name}}"type="file" accept=".pdf" required="" id="{{form.form.id_for_label}}">
                    </div>
                    <div class="row g-0 py-4 justify-content-between">
                        <div class="d-grid col-md-4 col-sm-8 col-6 mx-auto">
                            <input type="submit" class="btn btn-outline-dark" value="Upload">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock %}